#!/usr/bin/env bash
# akoi-installer - shell script to install akoi
# https://github.com/suzuki-shunsuke/akoi-installer

set -eu

VERSION=${VERSION:-v2.2.1} # renovate: depName=suzuki-shunsuke/akoi
INSTALL_PATH=${INSTALL_PATH:-.akoi/bin/akoi}

uname_os() {
  local os
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
  esac
  echo "$os"
}

uname_arch() {
  local arch
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo ${arch}
}

OS="$(uname_os)"
ARCH="$(uname_arch)"
mkdir -p "$(dirname "$INSTALL_PATH")"
echo "===> Installing akoi $VERSION ($OS/$ARCH) to $INSTALL_PATH ..." >&2
curl --fail -L "https://github.com/suzuki-shunsuke/akoi/releases/download/${VERSION}/akoi_${VERSION##v}_${OS}_${ARCH}" -o "$INSTALL_PATH"
chmod a+x "$INSTALL_PATH"
