---
name: test
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install akoi
        uses: ./
      - run: .akoi/bin/akoi --version

      - name: Install akoi version v2.2.0
        uses: ./
        with:
          version: 'v2.2.0'
      - run: .akoi/bin/akoi --version

      - name: Install akoi on dist/akoi
        uses: ./
        with:
          path: dist/akoi
      - run: dist/akoi --version

      - name: Install akoi on dist/akoi version 2.2.0
        uses: ./
        with:
          version: 'v2.2.0'
          path: dist/akoi
      - run: dist/akoi --version
